/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dal.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Orcamento;

/**
 *
 * @author janae
 */
public class OrdemDeServico extends javax.swing.JFrame {

    Connection conn = new Conexao().connect();
    PreparedStatement pstm;
    ResultSet rs;

    /**
     * Creates new form OrdemDeServico
     */
    public OrdemDeServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnConcluir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdemServ = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver Ordem de Serviços");
        setResizable(false);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Ordem De Serviços");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/calcular 128px.png"))); // NOI18N

        btnDeletar.setBackground(new java.awt.Color(204, 204, 204));
        btnDeletar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Ver Prontas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnConcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnConcluir.setText("Concluir");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton5.setText("Pendentes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tblOrdemServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF Cliente", "CPF Mecanico", "Valor", "Serviço"
            }
        ));
        tblOrdemServ.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblOrdemServAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblOrdemServ);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar)
                    .addComponent(jButton2)
                    .addComponent(btnConcluir)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TelaGerente tg = new TelaGerente();
        tg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        DefaultTableModel dtmTabela = (DefaultTableModel) tblOrdemServ.getModel();
        Object id = dtmTabela.getValueAt(tblOrdemServ.getSelectedRow(), 0);
        try {
            String sql = "delete from tbl_orçamento where Id_Orçamento = ?";
            pstm = conn.prepareStatement(sql);
            pstm.setObject(1, id);
            pstm.execute();
            pstm.close();
            JOptionPane.showMessageDialog(null, "Deletado");
            atualizarTabela();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblOrdemServ.getModel();
        ArrayList<Orcamento> lista = new ArrayList();
        model.getDataVector().removeAllElements();
        try {

            String sql = "select * from tbl_orçamento where Pronto = 1 and OrdemServico = 1";
            pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();
            lista.clear();
            while (rs.next()) {
                Orcamento orca = new Orcamento();
                orca.setId_orcamento(rs.getInt("Id_Orçamento"));
                orca.setValor(rs.getString("Valor"));
                orca.setCpfCliente(rs.getString("CPF_Cliente"));
                orca.setCpfMecanico(rs.getString("CPF_Mecanico"));
                orca.setServiços(rs.getString("Serviço"));
                lista.add(orca);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        for (Orcamento o : lista) {
            Object[] dados = {o.getId_orcamento(), o.getValor(), o.getCpfCliente(), o.getCpfMecanico(), o.getServiços()};
            model.addRow(dados);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblOrdemServAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblOrdemServAncestorAdded
        atualizarTabela();
    }//GEN-LAST:event_tblOrdemServAncestorAdded

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        DefaultTableModel dtmTabela = (DefaultTableModel) tblOrdemServ.getModel();
        Object id = dtmTabela.getValueAt(tblOrdemServ.getSelectedRow(), 0);
        try {
            String sql = "update tbl_orçamento set Pronto = 1 where Id_Orçamento = ?";
            pstm = conn.prepareStatement(sql);
            pstm.setObject(1, id);
            pstm.execute();
            pstm.close();
            JOptionPane.showMessageDialog(null, "Concluido");
            atualizarTabela();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        atualizarTabela();  
    }//GEN-LAST:event_jButton5ActionPerformed

    public void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tblOrdemServ.getModel();
        ArrayList<Orcamento> lista = new ArrayList();
        model.getDataVector().removeAllElements();
        try {

            String sql = "select * from tbl_orçamento where OrdemServico = 1 and Pronto = 0";
            pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();
            lista.clear();
            while (rs.next()) {
                Orcamento orca = new Orcamento();
                orca.setId_orcamento(rs.getInt("Id_Orçamento"));
                orca.setValor(rs.getString("Valor"));
                orca.setCpfCliente(rs.getString("CPF_Cliente"));
                orca.setCpfMecanico(rs.getString("CPF_Mecanico"));
                orca.setServiços(rs.getString("Serviço"));
                lista.add(orca);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        for (Orcamento o : lista) {
            Object[] dados = {o.getId_orcamento(), o.getValor(), o.getCpfCliente(), o.getCpfMecanico(), o.getServiços()};
            model.addRow(dados);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemDeServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrdemServ;
    // End of variables declaration//GEN-END:variables
}
