/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dal.Conexao;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author janae
 */
public class VerCliente extends javax.swing.JFrame {

    Connection conn = new Conexao().connect();
    PreparedStatement pstm;
    ResultSet rs;

    /**
     * Creates new form VerCliente
     */
    public VerCliente() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizar Clientes");
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Ver Clientes");

        btnDeletar.setBackground(new java.awt.Color(204, 204, 204));
        btnDeletar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF", "E-Mail", "Endereço", "Placa"
            }
        ));
        tblCliente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblClienteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblCliente);
        tblCliente.getAccessibleContext().setAccessibleName("Tabela Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnDeletar))
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(btnDeletar)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaGerente tg = new TelaGerente();
        tg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblClienteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblClienteAncestorAdded
        atualizarTabela();
    }//GEN-LAST:event_tblClienteAncestorAdded

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        DefaultTableModel dtmTabela = (DefaultTableModel) tblCliente.getModel();
        Object id = dtmTabela.getValueAt(tblCliente.getSelectedRow(), 0);
        try {
            String sql = "delete from tbl_cliente where Id_Cliente = ?";
            pstm = conn.prepareStatement(sql);
            pstm.setObject(1, id);
            pstm.execute();
            pstm.close();
            rs.close();
            JOptionPane.showMessageDialog(null, "Deletado");
            atualizarTabela();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"erro: " + e);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    public void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tblCliente.getModel();
        ArrayList<Cliente> lista = new ArrayList();
        model.setRowCount(0);
        try {

            String sql = "select * from tbl_cliente";
            pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();
            System.out.println(rs.getString("Nome"));
            while (rs.next()) {
                Cliente clien = new Cliente();
                clien.setId(rs.getInt("Id_Cliente"));
                clien.setNome(rs.getString("Nome"));
                clien.setTelefone(rs.getString("Telefone"));
                clien.setCPF(rs.getString("CPF"));
                clien.setEmail(rs.getString("Email"));
                clien.setEndereço(rs.getString("Endereço"));
                clien.setPlaca(rs.getString("Placa"));
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Erro no atualizar 01: " + e);
        } finally {
            try {
                pstm.close();
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro no atualizar: " + e);
            }
        }

        for (Cliente c : lista) {
            Object[] dados = {c.getId(), c.getNome(), c.getTelefone(), c.getCPF(), c.getEmail(), c.getEndereço(), c.getPlaca()};
            model.addRow(dados);
        } 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("assets/essavai.png")));
    }
}
